/**
 * Code is auto-generated by Application Logic, DO NOT EDIT.
 * @version(2.0)
 */
const LCAPApplicationService = require('@sap/low-code-event-handler');
const customermessage_Logic_PreprocessMessages = require('./code/customermessage-logic-preprocessMessages');

class arifZamri_StudentH53Srv extends LCAPApplicationService {
    async init() {

        this.before('READ', 'CustomerMessages', async (request) => {
            await customermessage_Logic_PreprocessMessages(request);
        });

        return super.init();
    }
}


module.exports = {
    arifZamri_StudentH53Srv
};